#pragma once

#include <SFML/Graphics.hpp>

using namespace sf;

enum OS {OS_WINDOWS, OS_LINUX, OS_MAC, OS_OTHER};

enum ScenesList {SCENE_MENU, SCENE_INFO, SCENE_GAME, SCENE_PAUSED, SCENE_LEVELUP, SCENE_GAMEOVER, SCENE_LEADERBOARD, EXIT = -1};

extern Color COLOR_BACKGROUND;
enum MovementKey {MOVEMENT_UP, MOVEMENT_DOWN, MOVEMENT_LEFT, MOVEMENT_RIGHT};
enum MouseButton {MOUSE_LEFT, MOUSE_LRIGHT};
enum ZombieType {ZOMBIE_NORMAL, ZOMBIE_BOOMER, ZOMBIE_HUNTER};
enum ZombieMoveStyle {ZOMBIE_MOVESTYLE_LINEAR, ZOMBIE_MOVESTYLE_XFIRST, ZOMBIE_MOVESTYLE_YFIRST, ZOMBIE_MOVESTYLE_RANDOM};
enum PickupsType {PICKUPS_HEALTH, PICKUPS_AMMO, PICKUPS_SPEED, PICKUPS_SCORE};
extern int ZombieDifficulty[sizeof(ZombieType)];
extern int currentLevel;
extern bool paused;